version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
    volumes:
      - ./backend:/app/source
    networks:
      - candlewise-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend/api
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/source
      - /app/source/node_modules
      - /app/source/.next
    networks:
      - candlewise-network

networks:
  candlewise-network:
    driver: bridge

volumes:
  frontend_node_modules:
